### ISSUE TITLE
connexion error

### ISSUE THREAD

**Issue by VictorTagayun** [CoderBotOrg/backend#115]
I used 2018-03-13-raspbian-stretch-lite.zip and when I run "python3 init.py"

```
(coderbot) pi@raspberrypi:~/coderbot $ python3 init.py
Traceback (most recent call last):
  File "init.py", line 23, in <module>
    import main
  File "/home/pi/coderbot/main.py", line 11, in <module>
    import connexion
ImportError: No module named 'connexion'
```

got this error

**Comment by avivace** [comment]
Did you run those commands before trying to start up the backend?

```
# Install the basic requirements
pip3 install -r requirements_stub.txt
# Additional packages if you are running the real thing
pip3 install -r requirements.txt
```

**Comment by VictorTagayun** [comment]
I always follow the wiki.

[https://github.com/CoderBotOrg/backend/wiki/Deploy-the-Python-Application](https://github.com/CoderBotOrg/backend/wiki/Deploy-the-Python-Application)

**Comment by avivace** [comment]
Woops, it is outdated.

Please try running both `pip3 install -r requirements_stub.txt` and `pip3 install -r requirements.txt` and report back.

I'll fix the wiki
