### ISSUE TITLE
Unable to access web application page

### ISSUE THREAD

**Issue by grandangelo** [CoderBotOrg/backend#123]
Raspbian Stretch upgraded.
Requirements installed via 
`pip3 install -r requirements_stub.txt`
`pip3 install -r requirements.txt`
Starting application with `python3 init.py`
`INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)`

Is not possible to browse to localhost:5000.

Any help appreciated.

**Comment by avivace** [comment]
What do you see if you try to access localhost:5000?

You have to place a build of the Vue app in a folder called "dist".

As the readme specifies:
> New Vue web application: [localhost:5000/](http://localhost:5000/) (assuming a [vue-app](https://github.com/coderbotorg/vue-app) build is placed in the `dist/` folder);

**Comment by grandangelo** [comment]
Error is `ERR_CONNECTION_REFUSED`.
Following instruction to setup  a vue-app (sorry did not noticed), after cloning repo:
`pi@coderbot:~/vue-app $ npm install
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.9.35-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/vue-app
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/vue-app/npm-debug.log
npm ERR! not ok code 0`

**Comment by avivace** [comment]
This is likely caused by a really old version of node/npm..

Are you trying to build the vue-app on the raspberry pi? This is discouraged and not supported, if you can, launch the build on another system then just move the dist folder on the raspberry.

However, you can find ready builds in the releases page of the vue-app repository, https://github.com/CoderBotOrg/vue-app/releases. Just download the more recent one and extract it, you should have the folder as if you built it yourself

**Comment by grandangelo** [comment]
Downloaded the release as suggested but 

pi@coderbot:~/vue-app $ npm run build

> vue-app@0.1.0 build /home/pi/vue-app
> node build/build.js

module.js:339
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/pi/vue-app/build/check-versions.js:2:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

npm ERR! vue-app@0.1.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-app@0.1.0 build script.
npm ERR! This is most likely a problem with the vue-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls vue-app
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.9.35-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! cwd /home/pi/vue-app
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/vue-app/npm-debug.log
npm ERR! not ok code 0

I will try to compile on my machine. Thanks for support.

**Comment by avivace** [comment]
Sorry, didn't make myself clear: 
vue-app-dist.tgz already contains the build web application. Exract it and you should see a "dist" folder. Just move it in the backend folder and you're good to go.

**Comment by grandangelo** [comment]
I cloned vue app repo, then extracted vue-app-dist in the same folder (I saw dist directory appear) and tried to start with 
`npm run build`
The output I posted comes from this procedure.

I will try to extract in a clean folder, then run 
 `npm run build`

**Comment by avivace** [comment]
Exactly, the release contains the *result* of npm run build.

Let me know!

**Comment by grandangelo** [comment]
I tried again but:

![image](https://user-images.githubusercontent.com/22768916/52968391-54686f80-33ad-11e9-9dab-513480c94808.png)
![image](https://user-images.githubusercontent.com/22768916/52968405-62b68b80-33ad-11e9-8c5e-da1797508323.png)

Any hint?

**Comment by avivace** [comment]
Try with `coderbot.local`

**Comment by grandangelo** [comment]
I removed vue-app directory, created again and copied dist folder after fresh download of prebuilt binary.
Browsing to http://coderbot.local:5000 redirects to http://coderbot.local:5000/vue/index.html and returns this json:

{
  "detail": "The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.",
  "status": 404,
  "title": "Not Found",
  "type": "about:blank"
}

**Comment by avivace** [comment]
This happens when the webserver can't find the vue-app build...
Are you sure you have a "dist" folder alongside the init.py script? and that folder contains the vue-app build (an index.html and some other files) ?

**Comment by avivace** [comment]
Gotcha, glad you figured that out
